/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PrivacyPolicy {
    }
}
declare global {
    interface HTMLPrivacyPolicyElement extends Components.PrivacyPolicy, HTMLStencilElement {
    }
    var HTMLPrivacyPolicyElement: {
        prototype: HTMLPrivacyPolicyElement;
        new (): HTMLPrivacyPolicyElement;
    };
    interface HTMLElementTagNameMap {
        "privacy-policy": HTMLPrivacyPolicyElement;
    }
}
declare namespace LocalJSX {
    interface PrivacyPolicy {
    }
    interface IntrinsicElements {
        "privacy-policy": PrivacyPolicy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "privacy-policy": LocalJSX.PrivacyPolicy & JSXBase.HTMLAttributes<HTMLPrivacyPolicyElement>;
        }
    }
}
